rootProject.name = "text-rpg"

include(":application:main")
include(":application:shared")
include(":application:test-utils")
include(":application:mongo-db-access")
include(":application:mediator")
include(":application:account")
include(":application:account:account-contract")
include(":application:event-store")
include(":application:event-store:event-store-contract")
include(":application:security")
include(":application:security:security-contract")
include(":application:mail")
include(":application:mail:mail-contract")
